[device]
vendor_id = 2290
product_id = 26641

[tablet]
resolution_x = 4096
resolution_y = 4096

[mapping]
mode = "Absolute"
tablet_left = 0
tablet_top = 0
tablet_right = 4095
tablet_bottom = 4095
screen_left = 0
screen_top = 0
screen_right = 4095
screen_bottom = 4095
force_proportions = false
rotation = 0
sensitivity_x = 1.0
sensitivity_y = 1.0

[orientation]
flip_x = false
flip_y = false
left_hand = false

[pressure]
touch_threshold = 1510
pressure_range = 530
max_pressure = 65535
min_pressure_threshold = 0
curve = "linear"
gamma = 1.0

[smoothing]
enabled = false
level = 3
anti_chatter = false
anti_chatter_threshold = 2

[buttons]
b1 = [
    "LEFTCTRL",
    "Z",
]
b2 = [
    "LEFTCTRL",
    "LEFTSHIFT",
    "Z",
]
b3 = ["P"]
b4 = ["E"]
b5 = ["V"]
b6 = ["H"]
b7 = ["DELETE"]
b8 = [
    "LEFTCTRL",
    "D",
]
b9 = [
    "LEFTCTRL",
    "A",
]
b10 = [
    "LEFTSHIFT",
    "1",
]
b11 = ["S"]
b12 = ["R"]

[pen_buttons]
stylus = "SCROLLUP"
eraser = "SCROLLDOWN"
tip = "BTN_LEFT"
